_BASE_: ../BDHNet_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "pretrained_weights/swin_base_patch4_window12_384_22k.pkl"
OUTPUT_DIR: "./experiments/BDH/BDHNet_swin_base_IN21k_384_bs16_50ep"