_BASE_: ../BDHNet_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "pretrained_weights/swin_small_patch4_window7_224.pkl"
OUTPUT_DIR: "./experiments/BDH/BDHNet_swin_small_bs16_50ep"